### PR TITLE
Update to 0.8.1 (with example)

### PR DESCRIPTION
**Pull request by christophercurrie**
This change updates the java8 module for the 0.8.1 patch release, and synchronizes some dependencies with that release.

It also updates the example project to dropwizard 8; it hadn't been updated from dropwizard 7.

### CODE REVIEW

**Comment by nqv** [comment]
@joschi Any reasons this PR hasn't been merged?

**Comment by joschi** [comment]
@nqv Basically just lack of time right now. But dropwizard-java8 0.8.0-1 should work perfectly fine with any version of Dropwizard 0.8.x (maybe you'll have to exclude some dependencies to make the Maven Enforcer plugin happy). Did you find any incompatibilities?

**Comment by christophercurrie** [comment]
A merge and release would be really helpful, not just because the dependencies wouldn't need to be managed, but because the `Instant` support would be very useful.

**Comment by joschi** [comment]
Closed because PR is out of date.

**Pull request closed without merging**
