### PR TITLE
Hibernate JSR-310 support requires Jadira User Types Extended

### PR DESCRIPTION
**Pull request by yunspace**
Added instructions on including http://jadira.sourceforge.net/usertype.extended/ when using Hibernate with JSR-310

### CODE REVIEW

**Comment by joschi** [comment]
This should probably be JSR-310 instead of JSR-130.

**Comment by yunspace** [comment]
hmm sorry typo... re-commit it?

**Comment by joschi** [comment]
@yunspace It's still wrong in the README.md. :wink:

**Comment by joschi** [comment]
Thanks!

**Pull request merged**
